### ISSUE TITLE
Loom video embed

### ISSUE THREAD

**Issue by regardtnel** [marcomontalbano/video-to-markdown#10]
Many clients give feedback via loom.com.  Would be great if we can add this as a supported format.

**Comment by marcomontalbano** [comment]
Hi @regardtnel,
thank you for the suggestion. I'll keep you posted.

**Comment by marcomontalbano** [comment]
Hi @regardtnel,
I added support to Loom. Please test it and let me know.
I'm using directly the thumbnails they provide. The tool will use the animated thumbnail `.gif` if available, if not it will fall back to the static `.jpg`.

**Comment by regardt-nel** [comment]
Hi @marcomontalbano thank you very much for adding support!

I just tested.  The video and playback displays, but it redirects to the loom page when clicked.

Is this the desired behaviour?

**Comment by marcomontalbano** [comment]
Hi @regardt-nel , yes that is the intended behavior. Unfortunately is not possibile to embed a video into a markdown as I explain in the `why` section. This project masks this missing feature creating a special thumbnail that looks like a video player.

**Comment by regardt-nel** [comment]
Understood! Thank you very much @marcomontalbano :)

**Comment by tonymj76** [comment]
how can i make use of this?
