### ISSUE TITLE
Want to suggest support for Wistia

### ISSUE THREAD

**Issue by christophcemper** [marcomontalbano/video-to-markdown#15]

**Comment by marcomontalbano** [comment]
Hi @christophcemper, thanks for interesting in this project.
I'll check the Wistia website and let you know.

**Comment by marcomontalbano** [comment]
Hi @christophcemper,
I just added support for Wistia.

Now you can `video-to-markdown` URLs like:
- https://support.wistia.com/medias/h1z3uqsjal
- https://wistia.com/series/brandwagon?wchannelid=u2joyabsw9&wvideoid=o54ad5d0t5
- http://fast.wistia.com/embed/iframe/26sk4lmiix
- ...

Let me know about any issue.
