### ISSUE TITLE
Provider request: CleanShot Cloud

### ISSUE THREAD

**Issue by eduwass** [marcomontalbano/video-to-markdown#24]
Hey Marco,

first of all congrats on the awesome tool, use it every day. 🤘

I see that you've already adopted some services that the people asked for.

So, if you happen to have some time, wanted to ask if you could make this Cleanshot Cloud compatible?

Here's an example link:

https://cln.sh/YRePNX

If it helps, I saw that in line 14 of the source code it has a link to the cover image:

     <meta property="og:image" content="https://cleanshot-cloud-fra.accelerator.net/media/3121/eeqN4r4PBAcP1mGyb16AM4rNpn83HjU78DxhZcAr.mp4;frame(1)/resize(1200,630,fit)/draw(image(b64-L2ludGVybmFsL3BsYXkucG5n),position:center).jpeg">

Would be awesome if you could integrate this.

Thanks!

**Comment by marcomontalbano** [comment]
Hi @eduwass, thanks a lot for your feedback. I really appreciated it!
I'll check on CleanShot Cloud and let you know.

**Comment by marcomontalbano** [comment]
Hi @eduwass, just pushed some changes to integrate with CleanShot.
A preview release is available at https://6043bf5b09b2a300088a0fa3--video-to-markdown.netlify.app/
Could you test it with some urls you have?
If everything is ok for you I'll then release it in prod.

Thanks

**Comment by eduwass** [comment]
Hey @marcomontalbano 

Thank you!!

I've tested with some URLs and seems to be working perfectly 👍

**Comment by marcomontalbano** [comment]
Many thanks for contributing to this tool.
I just released all the changes in prod.

**Comment by eduwass** [comment]
Awesome!!

Thanks to you! 🙏
