### ISSUE TITLE
support video from google drive/screencastify? 

### ISSUE THREAD

**Issue by jeanshotjack** [marcomontalbano/video-to-markdown#3]

**Comment by marcomontalbano** [comment]
Thanks @jeanshotjack for the request. I created the PR #4 for this.
Can you test this new feature on this environment? https://deploy-preview-4--video-to-markdown.netlify.com/
If everything is fine I'll promote the release to production.

**Comment by marcomontalbano** [comment]
Feature added to https://video-to-markdown.netlify.com/
