### ISSUE TITLE
Local Video File Option

### ISSUE THREAD

**Issue by shaneholloman** [marcomontalbano/video-to-markdown#33]
This strangely difficult on a windows machine inside VSCode! lol

**Comment by marcomontalbano** [comment]
Hi @shaneholloman , do you mean that it's hard running the project locally on windows machine? If so, I can check it. I never run it on windows.

**Comment by marcomontalbano** [comment]
Hi @shaneholloman,
I had the time to test this project locally on a Windows machine. After some attempts I was able to run it.

You can use [Git Bash](https://git-scm.com/downloads) or PowerShell (with PowerShell you have to change the Execution Policy).

You need to install [NodeJS 16.x](https://nodejs.org/en/) and [yarn](https://yarnpkg.com/getting-started/install#about-global-installs).

On Windows as soon as you run `yarn install` you probably will get this error message:

```sh
# gyp ERR! find VS **************************************************************
# gyp ERR! find VS You need to install the latest version of Visual Studio
# gyp ERR! find VS including the "Desktop development with C++" workload.
# gyp ERR! find VS For more information consult the documentation at:
# gyp ERR! find VS https://github.com/nodejs/node-gyp#on-windows
# gyp ERR! find VS **************************************************************
```

You can just follow the instructions at https://github.com/nodejs/node-gyp#on-windows
* Install the current version of Python from the Microsoft Store package.
* Install Visual Studio Build Tools 2019.
* Launch `npm config set msvs_version 2019`.

That's all, after these steps you'll be able to run `yarn install` and `yarn start`.
