### ISSUE TITLE
Imgur

### ISSUE THREAD

**Issue by Snailedlt** [marcomontalbano/video-to-markdown#58]
https://imgur.com/

## Example
Gallery: https://imgur.com/gallery/0QZygSh
Video: https://i.imgur.com/VT1vCoz.mp4

**Comment by marcomontalbano** [comment]
Hi @Snailedlt, thanks for your request!

I just added the `Imgur` provider. You can now get a picture with or without the play icon given a url similar to this one: https://imgur.com/VT1vCoz

You cannot get a single image from a gallery. You should click on "Copy link" (for each videos of the gallery) and paste the url into [Video to markdown!](https://video-to-markdown.marcomontalbano.com/)
<img width="294" alt="image" src="https://user-images.githubusercontent.com/1681269/204057260-968637eb-18e7-4e0d-92b0-f2bafaeafe93.png">

Regarding this specific format https://i.imgur.com/VT1vCoz.mp4, video-to-markdown is already able to generate an image from a generic `*.mp4` file.
