### ISSUE TITLE
support direct links to video files 

### ISSUE THREAD

**Issue by Vegita2** [marcomontalbano/video-to-markdown#6]
For example this one
https://i.imgur.com/vhjwXMB.mp4

The host should not matter.

**Comment by marcomontalbano** [comment]
Hi @Vegita2, thanks for this request and sorry for the delay in the response.
I create a PR #7 for this and a preview link is available at: https://5e1ce66bda0d3a00070a0ac1--video-to-markdown.netlify.com/
I'll push this PR in production at the end of the week.

As you can read in the PR description I implemented the solution client side to reduce quota usage. This means that you can encounter an error for this reason: `Access to video has been blocked by CORS policy`.

**Comment by Vegita2** [comment]
it works, thanks for implementing it so fast
