### ISSUE TITLE
Example Github Page With Video

### ISSUE THREAD

**Issue by MelbourneDeveloper** [marcomontalbano/video-to-markdown#8]
This looks like a great idea. Can we please see a Github page with an embedded video using this so we can see how it works?

**Comment by marcomontalbano** [comment]
Hi, this project aims to add the possibility to link a video on the markdown using a generated image that looks like a video player.
So you can have a markdown with a video that looks like an embedded one.
Just like this:

[![Big Buck Bunny 60fps 4K - Official Blender Foundation Short Film by Blender](https://res.cloudinary.com/marcomontalbano/image/upload/v1580417771/video_to_markdown/images/youtube--aqz-KE-bpKQ-c05b58ac6eb4c4700831b2b3070cd403.jpg)](https://m.youtube.com/watch?v=aqz-KE-bpKQ "Big Buck Bunny 60fps 4K - Official Blender Foundation Short Film by Blender")

Using GitHub Pages you are hosting a static website. In this case, you can directly embed a video from Youtube or any other sources without using video-to-markdown.

Instead, if you just want a link to the video on your website, you can download the generated image from video-to-markdown and use it inside your website.

Let me know if this answers your question.
